---
- name: Add repo file
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644

- name: Install MariaDB
  yum:
    enablerepo: mariadb
    state: present
    name:
      - MariaDB-server
      - MariaDB-client

- name: Install MySQLdb Python package for secure installations.
  yum:
    state: present
    name: MySQL-python
  when: mysql_secure_installation and mysql_root_password is defined
