---
  - name: Install yum packages
    yum:
      state: present
      name:
        - redis
    when: ansible_os_family == 'RedHat'

  # Prerequisite for Debian and Ubuntu
  - name: Install apt packages
    apt:
      state: present
      force: yes
      pkg:
        - redis-server
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  # Prerequisite for MACOS
  - name: install prequisites for macos
    homebrew:
      state: present
      name:
        - redis
    when: ansible_distribution == 'MacOSX'
...
